#!name=Apple WLOC 定位修改 (重定向版)
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭) - 伦敦全域强制生效版
#!author=hankinsus Rewrite
#!homepage=https://github.com/hankinsus/wloc
#!icon=https://raw.githubusercontent.com/hankinsus/wloc/refs/heads/main/wloc.jpg
#!category=Tools

[Script]
# 直接拦截苹果定位请求，重定向返回伦敦坐标
Apple WLOC = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,script-path=https://raw.githubusercontent.com/hankinsus/wloc/refs/heads/main/dist/wloc-redirect.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com